### PR TITLE
R4/develop

### PR DESCRIPTION
**Pull request by ivansager**
There is a problem with the compiler build coping to the tfr\bin\roslyn\ directory, but rather the {outdir}\roslyn\ directory

Add the following to the spark.cproj file
```
<Target Name="CopyRoslynFiles" AfterTargets="AfterBuild" Condition="!$(Disable_CopyWebApplication) And '$(OutDir)' != '$(OutputPath)'">
    <ItemGroup>
      <RoslynFiles Include="$(CscToolPath)\*" />
    </ItemGroup>
    <MakeDir Directories="$(WebProjectOutputDir)\bin\roslyn" />
    <Copy SourceFiles="@(RoslynFiles)" DestinationFolder="$(WebProjectOutputDir)\bin\roslyn" SkipUnchangedFiles="true" Retries="$(CopyRetryCount)" RetryDelayMilliseconds="$(CopyRetryDelayMilliseconds)" />
</Target>
```

### CODE REVIEW

**Comment by kennethmyhra** [comment]
@ivansager Can you explain a little more what kind of problem you are experiencing. In my environment without your addition to .csproj the roslyn files are copied to the directory bin\roslyn

**Comment by ivansager** [comment]
Hey @kennethmyhra thanks for the reply.

The error I received after cloning the repo and compiling (vs2017) was 
Could not find a part of the path '\bin\roslyn\csc.exe'.

Adding the Target I mentioned resolved the issue.

Lemme know if that helps.
Cheers,
Ivan

**Comment by kennethmyhra** [comment]
@ivansager I have removed the reference to Microsoft.CodeDom.Providers.DotNetCompilerPlatform, this should fix your problem. I am unsure why the reference was added in the first place and at the moment I do not see the need for it.

#148 contains the fix. Currently only fixed against DSTU2, but I will forward the changes to STU3 and R4 and let you know.

**Comment by ivansager** [comment]
Thanks, @kennethmyhra -- yeah, that is perfect, weird how Microsoft.CodeDom.Providers.DotNetCompilerPlatform wrangled its way into the check-in 

All good much thanks!

**Pull request closed without merging**
