### PR TITLE
Dstu2/develop

### PR DESCRIPTION
**Pull request by brianpos**
Some bug fixes that I've done, HTML rendering view and update to the latest nuget packages (except for Mongo)

### CODE REVIEW

**Comment by kennethmyhra** [comment]
@brianpos Thanks for these fixes!

I have cherry-picked most of these except for the commits related to htmlformatter and htmlview + the MongoDB DateTimeOffsetSerializer.

I would like to pull the MongoDB DateTimeOffsetSerializer commit, but unsure if it still is relevant/safe. I myself haven't yet noticed any date/time serialization issues.

* How can I reproduce the error?
* Would there be any backward compatibility issues with existing databases?

**Comment by brianpos** [comment]
A shame to leave the htmlformatter out, gives you a convenient html view when interacting with the browser only.

**Comment by brianpos** [comment]
The datetimeformatter was some conpatability issue with newer versions of mongoDB. If it's working, no need I guess.

**Comment by kennethmyhra** [comment]
Thanks again, Brian! I'll have a look into the htmlformatter, didn't try to merge it yet.

**Comment by kennethmyhra** [comment]
Closing this, most of the fixes have been re-applied or cherry-picked

**Pull request closed without merging**
