### PR TITLE
Fix multi include reinclude from query

### PR DESCRIPTION
**Pull request by whyfate**
now，I search use include
// it's success
`http://spark.kufu.no/fhir/ServiceRequest?_id:exact=ambulation&_include=ServiceRequest:encounter`

// it's fail
`http://spark.kufu.no/fhir/ServiceRequest?_id:exact=ambulation&_include=ServiceRequest:encounter&_include=ServiceRequest:subject&_include=ServiceRequest:requester`

### CODE REVIEW

**Comment by kennethmyhra** [comment]
@whyfate This PR #277 was supposedly fixing the problem you are experiencing. But as I understand, according to your PR, it doesn't and the fix you are proposing has been tested and works?

**Comment by whyfate** [comment]
@kennethmyhra I think I might know your question,The problem is `HttpRequest`.But unit testing does not cover this.

**Comment by whyfate** [comment]
The PR #277 only fix the problem of `HttpRequestMessage`.

**Comment by whyfate** [comment]
It was my fault. After I found out the problem with `Httprequest`, I rashly modified the `HttpRequestMessage`, which caused this misunderstanding.

**Comment by kennethmyhra** [comment]
@whyfate I actually like your fix better. It uses an already existing method from the firely-net-sdk, and the code is now similar for both methods.

One thing though, could you recreate a PR and target stu3/master instead of r4/master? If you do that I can forward merge your fix to R4

**Comment by whyfate** [comment]
OK

**Comment by kennethmyhra** [comment]
Thanks, merged #313

**Pull request closed without merging**
